setup a flow that reuses set_status – resolves #132
c745fd2: set-status --pin stable - #132

0dc1934: undo - #132

8caeee8: lets see it fail too - #132

695b834: using a gh extension - #132

5c72814: one quote too many - #132

fad9d33: pretty up the script - #132

66d4997: need permissions - #132

d040e92: Token wasn't set - #132

0c02a79: ECHO in capital - #132

a1b7b2e: quote problems - #132

b1e682b: token problems? - #132

94e72dd: simplify script by sourcing it - #132

c0c0b6a: pwd + env - #132

367df21: wrong location - #132

9540c5e: no space allowed - #132

56dc193: use set - #132

4911e74: check the env - #132

f278075: test the helper script - #132

21f086e: test the success too - #132

b49f758: capture the result - #132

9e40b19: simpler, more readable - pass the exitcode - #132

3f6c299: simpler, more readable - #132

fedd43b: dont die on error - report it - don't ignore it - #132

4542860: dont die on error - report it - #132

8409b9a: run from main - #132

dedc54e: if always - #132

5a42efc: provok a failed test coverage - #132

af37498: changed the loaction of the flow - #132

6195dce: changed the job name - #132

9b3647d: using v1 of the flow - #132

7d0ad38: setup venv - #132

e0b5de1: Testing my flow - #132

diff --git a/.github/workflows/wrapup.yml b/.github/workflows/wrapup.yml
--- a/.github/workflows/wrapup.yml
+++ b/.github/workflows/wrapup.yml
@@ -10,27 +10,55 @@ on:
     branches: 
       - '[0-9]*'
 
+# No special permissions defined before we need them
 permissions:
   contents: read
 
 jobs:
-  build:
+  # This job will install uv, run the unittests and output the arguments we need to set the status
+  verification:
 
     runs-on: ubuntu-latest
+    permissions:
+      statuses: write
+
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python 3.13
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.13"
-    - name: Install uv and dependencies
-      run: |
-        curl -LsSf https://astral.sh/uv/install.sh | sh
-        uv venv
-        source .venv/bin/activate
-        uv sync --extra dev
-    - name: Test with pytest
-      run: |
-        . .venv/bin/activate 
-        pytest --cov=. --cov-config=.coveragerc -m unittest
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Python 3.13
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.13"
+
+      - name: Install dependencies
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          curl -LsSf https://astral.sh/uv/install.sh | sh
+          uv venv
+          . .venv/bin/activate
+          uv sync --extra dev
+          gh extension install thetechcollective/gh-set-status --pin stable
+
+      - name: Test with pytest
+        id: Unittest
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          . .venv/bin/activate 
+          pwd
+          # Dont exit if the next command fails, we want to capture the exit code
+          set +e
+          pytest --cov=. --cov-config=.coveragerc -m unittest
+          result=$?
+          set -e
+
+
+          if [ $result -eq 0 ]; then
+            gh set-status success "All tests passed and threshold on line coverage reached"
+          else
+            gh set-status failure "Some tests failed or threshold on line covearage not reached"
+          fi
+          exit $result
